name: Lint Code Base

on:
  pull_request:
    branches: [gh-pages, averdin2-1441-scss-lint-gh-action]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: averdin2-1441-scss-lint-gh-action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          LINTER_RULES_PATH: /
          CSS_FILE_NAME: .stylelintrc.json
          VALIDATE_CSS: true
